/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cursoemvideo;

/**
 *
 * @author Cassio
 */
public class TipoDeTriangulo extends javax.swing.JFrame {

    /**
     * Creates new form TipoDeTriangulo
     */
    public TipoDeTriangulo() {
        initComponents();
        pnlResposta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlResposta = new javax.swing.JPanel();
        lblFormaNaoForma = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sldA = new javax.swing.JSlider();
        sldC = new javax.swing.JSlider();
        sldB = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFormaNaoForma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblFormaNaoForma.setForeground(new java.awt.Color(0, 0, 255));
        lblFormaNaoForma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormaNaoForma.setText("0");

        lblTipo.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("0");

        javax.swing.GroupLayout pnlRespostaLayout = new javax.swing.GroupLayout(pnlResposta);
        pnlResposta.setLayout(pnlRespostaLayout);
        pnlRespostaLayout.setHorizontalGroup(
            pnlRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormaNaoForma, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(lblTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlRespostaLayout.setVerticalGroup(
            pnlRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormaNaoForma, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblTipo))
        );

        getContentPane().add(pnlResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, 380, -1));

        btnVerificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerificar.setText("VERIFICAR");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Lado A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Lado B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Lado C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        sldA.setMaximum(15);
        sldA.setValue(0);
        sldA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldAStateChanged(evt);
            }
        });
        getContentPane().add(sldA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        sldC.setMaximum(15);
        sldC.setValue(0);
        sldC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldCStateChanged(evt);
            }
        });
        getContentPane().add(sldC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        sldB.setMaximum(15);
        sldB.setValue(0);
        sldB.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sldB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldBStateChanged(evt);
            }
        });
        getContentPane().add(sldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/triangulo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        lblA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblA.setText("0");
        getContentPane().add(lblA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        lblB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblB.setText("0");
        getContentPane().add(lblB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        lblC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblC.setText("0");
        getContentPane().add(lblC, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        int segA = sldA.getValue();
        int segB = sldB.getValue();
        int segC = sldC.getValue();
        
        pnlResposta.setVisible(true);
        if (segA<segB+segC && segB<segA+segC && segC<segA+segB) {
            lblFormaNaoForma.setText("É um triângulo");
            if ((segA == segB) && (segB == segC)){
            lblFormaNaoForma.setText("É um triângulo");
            lblTipo.setText("EQUILÁTERO");
            } else if ((segA == segB) || (segB == segC) || (segC == segA)) {
                lblFormaNaoForma.setText("É um triângulo");
                lblTipo.setText("ISÓSCELES");
            } else {
                lblFormaNaoForma.setText("É um triângulo");
                lblTipo.setText("ESCALENO");
            }
        } else {
            lblFormaNaoForma.setText("NÃO É UM TRIÂNGULO");
            lblTipo.setText("...");
        } 
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void sldAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldAStateChanged
        int segA = sldA.getValue();
        lblA.setText(String.valueOf(segA));
    }//GEN-LAST:event_sldAStateChanged

    private void sldBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldBStateChanged
        int segB = sldB.getValue();
        lblB.setText(String.valueOf(segB));
    }//GEN-LAST:event_sldBStateChanged

    private void sldCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldCStateChanged
        int segC = sldC.getValue();
        lblC.setText(String.valueOf(segC)); 
    }//GEN-LAST:event_sldCStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoDeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoDeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoDeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoDeTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoDeTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblFormaNaoForma;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlResposta;
    private javax.swing.JSlider sldA;
    private javax.swing.JSlider sldB;
    private javax.swing.JSlider sldC;
    // End of variables declaration//GEN-END:variables
}
